#!/bin/sh
# asuskblctl v0.1
#
# Copyright (c) 2014, Amadeus FOlego <amadeusfolego@gmail.com>
# All rights reserved.

backlights_path='/sys/class/leds/asus::kbd_backlight'
max_brightness="$(< ${backlights_path}/max_brightness)"
current_brightness="$(< ${backlights_path}/brightness)"

adjust_brightness() {
  if [ "$1" -gt "${max_brightness}" ]; then
    new_value="${max_brightness}"
  elif [ "$1" -lt '0' ]; then
    new_value="0"
  else
    new_value="$1"
  fi
  echo "${new_value}" | tee "${backlights_path}/brightness"
}

printhelp() {
  name="${0##*/}"
  echo " * ${name} v0.1

  ${name} up
    brightness +1

  ${name} down
    brightness -1

  ${name} full
    full brightness

  ${name} off
    turn off brightness (set to 0)

  ${name} set <n>
    set brightness to <n>

  ${name} get
    get brightness value
"
}

case "$1" in
  up)
    adjust_brightness "$((${current_brightness}+1))"
  ;;
  down)
    adjust_brightness "$((${current_brightness}-1))"
  ;;
  off)
    adjust_brightness '0'
  ;;
  full)
    adjust_brightness "${max_brightness}"
  ;;
  set)
    if [ -n "$2" ] && [[ "$2" =~ ^[0-9]+$ ]]; then
      adjust_brightness "$2"
    else
      echo "set needs numeric second argument."; exit 1
    fi
  ;;
  get)
    echo ${current_brightness}
  ;;
  *)
    printhelp; exit 1
  ;;
esac
