#!/bin/sh
# asuskblctl v0.1
#
# Copyright (c) 2014, Amadeus Folego <amadeusfolego@gmail.com>
# All rights reserved.
backlights_path='/sys/class/leds/asus::kbd_backlight'
brightness_file="${backlights_path}/brightness"
max_brightness_file="${backlights_path}/max_brightness"
max_brightness="$(< ${max_brightness_file})"
current_brightness="$(< ${brightness_file})"

adjust_brightness() {
  if [ "$1" -gt "${max_brightness}" ]; then
    new_value="${max_brightness}"
  elif [ "$1" -lt '0' ]; then
    new_value="0"
  else
    new_value="$1"
  fi
  echo "${new_value}" | tee "${brightness_file}"
}

wait_for() {
  max_tries=100

  if [ ! -f $1 ]; then echo "Waiting for: $1"; fi

  for n in $(seq 1 ${max_tries})
  do
    if [ -f $1 ]; then break; fi
    printf "."
    sleep 1
  done
  `$2`
}

printhelp() {
  name="${0##*/}"
  echo " * ${name} v0.1

  ${name} up
    brightness +1

  ${name} down
    brightness -1

  ${name} full
    full brightness

  ${name} off
    turn off brightness (set to 0)

  ${name} set <n>
    set brightness to <n>

  ${name} get
    get brightness value

  ${name} permissions
    get go+w permissions on the control files
"
}

case "$1" in
  up)
    adjust_brightness "$((${current_brightness}+1))"
  ;;
  down)
    adjust_brightness "$((${current_brightness}-1))"
  ;;
  off)
    adjust_brightness '0'
  ;;
  full)
    adjust_brightness "${max_brightness}"
  ;;
  set)
    if [ -n "$2" ] && [[ "$2" =~ ^[0-9]+$ ]]; then
      adjust_brightness "$2"
    else
      echo "set needs numeric second argument."; exit 1
    fi
  ;;
  get)
    echo ${current_brightness}
  ;;
  permissions)
    wait_for ${brightness_file} "chmod go+w ${brightness_file}"
    wait_for ${max_brightness_file} "chmod go+r ${max_brightness_file}"
  ;;
  *)
    printhelp; exit 1
  ;;
esac
